// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/input.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Serving {

  /// <summary>Holder for reflection information generated from tensorflow_serving/apis/input.proto</summary>
  public static partial class InputReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow_serving/apis/input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiN0ZW5zb3JmbG93X3NlcnZpbmcvYXBpcy9pbnB1dC5wcm90bxISdGVuc29y",
            "Zmxvdy5zZXJ2aW5nGiV0ZW5zb3JmbG93L2NvcmUvZXhhbXBsZS9leGFtcGxl",
            "LnByb3RvIjQKC0V4YW1wbGVMaXN0EiUKCGV4YW1wbGVzGAEgAygLMhMudGVu",
            "c29yZmxvdy5FeGFtcGxlImUKFkV4YW1wbGVMaXN0V2l0aENvbnRleHQSJQoI",
            "ZXhhbXBsZXMYASADKAsyEy50ZW5zb3JmbG93LkV4YW1wbGUSJAoHY29udGV4",
            "dBgCIAEoCzITLnRlbnNvcmZsb3cuRXhhbXBsZSKhAQoFSW5wdXQSOwoMZXhh",
            "bXBsZV9saXN0GAEgASgLMh8udGVuc29yZmxvdy5zZXJ2aW5nLkV4YW1wbGVM",
            "aXN0QgIoAUgAElMKGWV4YW1wbGVfbGlzdF93aXRoX2NvbnRleHQYAiABKAsy",
            "Ki50ZW5zb3JmbG93LnNlcnZpbmcuRXhhbXBsZUxpc3RXaXRoQ29udGV4dEIC",
            "KAFIAEIGCgRraW5kQgP4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorflow.ExampleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.Serving.ExampleList), global::Tensorflow.Serving.ExampleList.Parser, new[]{ "Examples" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.Serving.ExampleListWithContext), global::Tensorflow.Serving.ExampleListWithContext.Parser, new[]{ "Examples", "Context" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.Serving.Input), global::Tensorflow.Serving.Input.Parser, new[]{ "ExampleList", "ExampleListWithContext" }, new[]{ "Kind" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Specifies one or more fully independent input Examples.
  /// See examples at:
  ///     https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto
  /// </summary>
  public sealed partial class ExampleList : pb::IMessage<ExampleList> {
    private static readonly pb::MessageParser<ExampleList> _parser = new pb::MessageParser<ExampleList>(() => new ExampleList());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExampleList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.Serving.InputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleList(ExampleList other) : this() {
      examples_ = other.examples_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleList Clone() {
      return new ExampleList(this);
    }

    /// <summary>Field number for the "examples" field.</summary>
    public const int ExamplesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tensorflow.Example> _repeated_examples_codec
        = pb::FieldCodec.ForMessage(10, global::Tensorflow.Example.Parser);
    private readonly pbc::RepeatedField<global::Tensorflow.Example> examples_ = new pbc::RepeatedField<global::Tensorflow.Example>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Tensorflow.Example> Examples {
      get { return examples_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExampleList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExampleList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!examples_.Equals(other.examples_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= examples_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      examples_.WriteTo(output, _repeated_examples_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += examples_.CalculateSize(_repeated_examples_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExampleList other) {
      if (other == null) {
        return;
      }
      examples_.Add(other.examples_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            examples_.AddEntriesFrom(input, _repeated_examples_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Specifies one or more independent input Examples, with a common context
  /// Example.
  ///
  /// The common use case for context is to cleanly and optimally specify some
  /// features that are common across multiple examples.
  ///
  /// See example below with a search query as the context and multiple restaurants
  /// to perform some inference on.
  ///
  /// context: {
  ///   feature: {
  ///     key  : "query"
  ///     value: {
  ///       bytes_list: {
  ///         value: [ "pizza" ]
  ///       }
  ///     }
  ///   }
  /// }
  /// examples: {
  ///   feature: {
  ///     key  : "cuisine"
  ///     value: {
  ///       bytes_list: {
  ///         value: [ "Pizzeria" ]
  ///       }
  ///     }
  ///   }
  /// }
  /// examples: {
  ///   feature: {
  ///     key  : "cuisine"
  ///     value: {
  ///       bytes_list: {
  ///         value: [ "Taqueria" ]
  ///       }
  ///     }
  ///   }
  /// }
  ///
  /// Implementations of ExampleListWithContext merge the context Example into each
  /// of the Examples. Note that feature keys must not be duplicated between the
  /// Examples and context Example, or the behavior is undefined.
  ///
  /// See also:
  ///     tensorflow/core/example/example.proto
  ///     https://developers.google.com/protocol-buffers/docs/proto3#maps
  /// </summary>
  public sealed partial class ExampleListWithContext : pb::IMessage<ExampleListWithContext> {
    private static readonly pb::MessageParser<ExampleListWithContext> _parser = new pb::MessageParser<ExampleListWithContext>(() => new ExampleListWithContext());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExampleListWithContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.Serving.InputReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleListWithContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleListWithContext(ExampleListWithContext other) : this() {
      examples_ = other.examples_.Clone();
      Context = other.context_ != null ? other.Context.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExampleListWithContext Clone() {
      return new ExampleListWithContext(this);
    }

    /// <summary>Field number for the "examples" field.</summary>
    public const int ExamplesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tensorflow.Example> _repeated_examples_codec
        = pb::FieldCodec.ForMessage(10, global::Tensorflow.Example.Parser);
    private readonly pbc::RepeatedField<global::Tensorflow.Example> examples_ = new pbc::RepeatedField<global::Tensorflow.Example>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Tensorflow.Example> Examples {
      get { return examples_; }
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 2;
    private global::Tensorflow.Example context_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorflow.Example Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExampleListWithContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExampleListWithContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!examples_.Equals(other.examples_)) return false;
      if (!object.Equals(Context, other.Context)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= examples_.GetHashCode();
      if (context_ != null) hash ^= Context.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      examples_.WriteTo(output, _repeated_examples_codec);
      if (context_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Context);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += examples_.CalculateSize(_repeated_examples_codec);
      if (context_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Context);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExampleListWithContext other) {
      if (other == null) {
        return;
      }
      examples_.Add(other.examples_);
      if (other.context_ != null) {
        if (context_ == null) {
          context_ = new global::Tensorflow.Example();
        }
        Context.MergeFrom(other.Context);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            examples_.AddEntriesFrom(input, _repeated_examples_codec);
            break;
          }
          case 18: {
            if (context_ == null) {
              context_ = new global::Tensorflow.Example();
            }
            input.ReadMessage(context_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Input : pb::IMessage<Input> {
    private static readonly pb::MessageParser<Input> _parser = new pb::MessageParser<Input>(() => new Input());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Input> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.Serving.InputReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input(Input other) : this() {
      switch (other.KindCase) {
        case KindOneofCase.ExampleList:
          ExampleList = other.ExampleList.Clone();
          break;
        case KindOneofCase.ExampleListWithContext:
          ExampleListWithContext = other.ExampleListWithContext.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Input Clone() {
      return new Input(this);
    }

    /// <summary>Field number for the "example_list" field.</summary>
    public const int ExampleListFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorflow.Serving.ExampleList ExampleList {
      get { return kindCase_ == KindOneofCase.ExampleList ? (global::Tensorflow.Serving.ExampleList) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.ExampleList;
      }
    }

    /// <summary>Field number for the "example_list_with_context" field.</summary>
    public const int ExampleListWithContextFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorflow.Serving.ExampleListWithContext ExampleListWithContext {
      get { return kindCase_ == KindOneofCase.ExampleListWithContext ? (global::Tensorflow.Serving.ExampleListWithContext) kind_ : null; }
      set {
        kind_ = value;
        kindCase_ = value == null ? KindOneofCase.None : KindOneofCase.ExampleListWithContext;
      }
    }

    private object kind_;
    /// <summary>Enum of possible cases for the "kind" oneof.</summary>
    public enum KindOneofCase {
      None = 0,
      ExampleList = 1,
      ExampleListWithContext = 2,
    }
    private KindOneofCase kindCase_ = KindOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KindOneofCase KindCase {
      get { return kindCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearKind() {
      kindCase_ = KindOneofCase.None;
      kind_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Input);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Input other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ExampleList, other.ExampleList)) return false;
      if (!object.Equals(ExampleListWithContext, other.ExampleListWithContext)) return false;
      if (KindCase != other.KindCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (kindCase_ == KindOneofCase.ExampleList) hash ^= ExampleList.GetHashCode();
      if (kindCase_ == KindOneofCase.ExampleListWithContext) hash ^= ExampleListWithContext.GetHashCode();
      hash ^= (int) kindCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (kindCase_ == KindOneofCase.ExampleList) {
        output.WriteRawTag(10);
        output.WriteMessage(ExampleList);
      }
      if (kindCase_ == KindOneofCase.ExampleListWithContext) {
        output.WriteRawTag(18);
        output.WriteMessage(ExampleListWithContext);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (kindCase_ == KindOneofCase.ExampleList) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExampleList);
      }
      if (kindCase_ == KindOneofCase.ExampleListWithContext) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExampleListWithContext);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Input other) {
      if (other == null) {
        return;
      }
      switch (other.KindCase) {
        case KindOneofCase.ExampleList:
          ExampleList = other.ExampleList;
          break;
        case KindOneofCase.ExampleListWithContext:
          ExampleListWithContext = other.ExampleListWithContext;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::Tensorflow.Serving.ExampleList subBuilder = new global::Tensorflow.Serving.ExampleList();
            if (kindCase_ == KindOneofCase.ExampleList) {
              subBuilder.MergeFrom(ExampleList);
            }
            input.ReadMessage(subBuilder);
            ExampleList = subBuilder;
            break;
          }
          case 18: {
            global::Tensorflow.Serving.ExampleListWithContext subBuilder = new global::Tensorflow.Serving.ExampleListWithContext();
            if (kindCase_ == KindOneofCase.ExampleListWithContext) {
              subBuilder.MergeFrom(ExampleListWithContext);
            }
            input.ReadMessage(subBuilder);
            ExampleListWithContext = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
