// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/debug.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/protobuf/debug.proto</summary>
  public static partial class DebugReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/protobuf/debug.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DebugReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiR0ZW5zb3JmbG93L2NvcmUvcHJvdG9idWYvZGVidWcucHJvdG8SCnRlbnNv",
            "cmZsb3cijgEKEERlYnVnVGVuc29yV2F0Y2gSEQoJbm9kZV9uYW1lGAEgASgJ",
            "EhMKC291dHB1dF9zbG90GAIgASgFEhEKCWRlYnVnX29wcxgDIAMoCRISCgpk",
            "ZWJ1Z191cmxzGAQgAygJEisKI3RvbGVyYXRlX2RlYnVnX29wX2NyZWF0aW9u",
            "X2ZhaWx1cmVzGAUgASgIImIKDERlYnVnT3B0aW9ucxI9ChdkZWJ1Z190ZW5z",
            "b3Jfd2F0Y2hfb3B0cxgEIAMoCzIcLnRlbnNvcmZsb3cuRGVidWdUZW5zb3JX",
            "YXRjaBITCgtnbG9iYWxfc3RlcBgKIAEoA0IsChhvcmcudGVuc29yZmxvdy5m",
            "cmFtZXdvcmtCC0RlYnVnUHJvdG9zUAH4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.DebugTensorWatch), global::Tensorflow.DebugTensorWatch.Parser, new[]{ "NodeName", "OutputSlot", "DebugOps", "DebugUrls", "TolerateDebugOpCreationFailures" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.DebugOptions), global::Tensorflow.DebugOptions.Parser, new[]{ "DebugTensorWatchOpts", "GlobalStep" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// EXPERIMENTAL. Option for watching a node.
  /// </summary>
  public sealed partial class DebugTensorWatch : pb::IMessage<DebugTensorWatch> {
    private static readonly pb::MessageParser<DebugTensorWatch> _parser = new pb::MessageParser<DebugTensorWatch>(() => new DebugTensorWatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DebugTensorWatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.DebugReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugTensorWatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugTensorWatch(DebugTensorWatch other) : this() {
      nodeName_ = other.nodeName_;
      outputSlot_ = other.outputSlot_;
      debugOps_ = other.debugOps_.Clone();
      debugUrls_ = other.debugUrls_.Clone();
      tolerateDebugOpCreationFailures_ = other.tolerateDebugOpCreationFailures_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugTensorWatch Clone() {
      return new DebugTensorWatch(this);
    }

    /// <summary>Field number for the "node_name" field.</summary>
    public const int NodeNameFieldNumber = 1;
    private string nodeName_ = "";
    /// <summary>
    /// Name of the node to watch.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NodeName {
      get { return nodeName_; }
      set {
        nodeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "output_slot" field.</summary>
    public const int OutputSlotFieldNumber = 2;
    private int outputSlot_;
    /// <summary>
    /// Output slot to watch.
    /// The semantics of output_slot == -1 is that the node is only watched for
    /// completion, but not for any output tensors. See NodeCompletionCallback
    /// in debug_gateway.h.
    /// TODO(cais): Implement this semantics.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OutputSlot {
      get { return outputSlot_; }
      set {
        outputSlot_ = value;
      }
    }

    /// <summary>Field number for the "debug_ops" field.</summary>
    public const int DebugOpsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_debugOps_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> debugOps_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Name(s) of the debugging op(s).
    /// One or more than one probes on a tensor.
    /// e.g., {"DebugIdentity", "DebugNanCount"}
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DebugOps {
      get { return debugOps_; }
    }

    /// <summary>Field number for the "debug_urls" field.</summary>
    public const int DebugUrlsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_debugUrls_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> debugUrls_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// URL(s) for debug targets(s).
    ///
    /// Supported URL formats are:
    ///   - file:///foo/tfdbg_dump: Writes out Event content to file
    ///     /foo/tfdbg_dump.  Assumes all directories can be created if they don't
    ///     already exist.
    ///   - grpc://localhost:11011: Sends an RPC request to an EventListener
    ///     service running at localhost:11011 with the event.
    ///   - memcbk:///event_key: Routes tensors to clients using the
    ///     callback registered with the DebugCallbackRegistry for event_key.
    ///
    /// Each debug op listed in debug_ops will publish its output tensor (debug
    /// signal) to all URLs in debug_urls.
    ///
    /// N.B. Session::Run() supports concurrent invocations of the same inputs
    /// (feed keys), outputs and target nodes. If such concurrent invocations
    /// are to be debugged, the callers of Session::Run() must use distinct
    /// debug_urls to make sure that the streamed or dumped events do not overlap
    /// among the invocations.
    /// TODO(cais): More visible documentation of this in g3docs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DebugUrls {
      get { return debugUrls_; }
    }

    /// <summary>Field number for the "tolerate_debug_op_creation_failures" field.</summary>
    public const int TolerateDebugOpCreationFailuresFieldNumber = 5;
    private bool tolerateDebugOpCreationFailures_;
    /// <summary>
    /// Do not error out if debug op creation fails (e.g., due to dtype
    /// incompatibility). Instead, just log the failure.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool TolerateDebugOpCreationFailures {
      get { return tolerateDebugOpCreationFailures_; }
      set {
        tolerateDebugOpCreationFailures_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DebugTensorWatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DebugTensorWatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NodeName != other.NodeName) return false;
      if (OutputSlot != other.OutputSlot) return false;
      if(!debugOps_.Equals(other.debugOps_)) return false;
      if(!debugUrls_.Equals(other.debugUrls_)) return false;
      if (TolerateDebugOpCreationFailures != other.TolerateDebugOpCreationFailures) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NodeName.Length != 0) hash ^= NodeName.GetHashCode();
      if (OutputSlot != 0) hash ^= OutputSlot.GetHashCode();
      hash ^= debugOps_.GetHashCode();
      hash ^= debugUrls_.GetHashCode();
      if (TolerateDebugOpCreationFailures != false) hash ^= TolerateDebugOpCreationFailures.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NodeName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NodeName);
      }
      if (OutputSlot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OutputSlot);
      }
      debugOps_.WriteTo(output, _repeated_debugOps_codec);
      debugUrls_.WriteTo(output, _repeated_debugUrls_codec);
      if (TolerateDebugOpCreationFailures != false) {
        output.WriteRawTag(40);
        output.WriteBool(TolerateDebugOpCreationFailures);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NodeName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NodeName);
      }
      if (OutputSlot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OutputSlot);
      }
      size += debugOps_.CalculateSize(_repeated_debugOps_codec);
      size += debugUrls_.CalculateSize(_repeated_debugUrls_codec);
      if (TolerateDebugOpCreationFailures != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DebugTensorWatch other) {
      if (other == null) {
        return;
      }
      if (other.NodeName.Length != 0) {
        NodeName = other.NodeName;
      }
      if (other.OutputSlot != 0) {
        OutputSlot = other.OutputSlot;
      }
      debugOps_.Add(other.debugOps_);
      debugUrls_.Add(other.debugUrls_);
      if (other.TolerateDebugOpCreationFailures != false) {
        TolerateDebugOpCreationFailures = other.TolerateDebugOpCreationFailures;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            NodeName = input.ReadString();
            break;
          }
          case 16: {
            OutputSlot = input.ReadInt32();
            break;
          }
          case 26: {
            debugOps_.AddEntriesFrom(input, _repeated_debugOps_codec);
            break;
          }
          case 34: {
            debugUrls_.AddEntriesFrom(input, _repeated_debugUrls_codec);
            break;
          }
          case 40: {
            TolerateDebugOpCreationFailures = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// EXPERIMENTAL. Options for initializing DebuggerState.
  /// </summary>
  public sealed partial class DebugOptions : pb::IMessage<DebugOptions> {
    private static readonly pb::MessageParser<DebugOptions> _parser = new pb::MessageParser<DebugOptions>(() => new DebugOptions());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DebugOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.DebugReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugOptions(DebugOptions other) : this() {
      debugTensorWatchOpts_ = other.debugTensorWatchOpts_.Clone();
      globalStep_ = other.globalStep_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DebugOptions Clone() {
      return new DebugOptions(this);
    }

    /// <summary>Field number for the "debug_tensor_watch_opts" field.</summary>
    public const int DebugTensorWatchOptsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Tensorflow.DebugTensorWatch> _repeated_debugTensorWatchOpts_codec
        = pb::FieldCodec.ForMessage(34, global::Tensorflow.DebugTensorWatch.Parser);
    private readonly pbc::RepeatedField<global::Tensorflow.DebugTensorWatch> debugTensorWatchOpts_ = new pbc::RepeatedField<global::Tensorflow.DebugTensorWatch>();
    /// <summary>
    /// Debugging options
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Tensorflow.DebugTensorWatch> DebugTensorWatchOpts {
      get { return debugTensorWatchOpts_; }
    }

    /// <summary>Field number for the "global_step" field.</summary>
    public const int GlobalStepFieldNumber = 10;
    private long globalStep_;
    /// <summary>
    /// Caller-specified global step count.
    /// Note that this is distinct from the session run count and the executor
    /// step count.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long GlobalStep {
      get { return globalStep_; }
      set {
        globalStep_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DebugOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DebugOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!debugTensorWatchOpts_.Equals(other.debugTensorWatchOpts_)) return false;
      if (GlobalStep != other.GlobalStep) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= debugTensorWatchOpts_.GetHashCode();
      if (GlobalStep != 0L) hash ^= GlobalStep.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      debugTensorWatchOpts_.WriteTo(output, _repeated_debugTensorWatchOpts_codec);
      if (GlobalStep != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(GlobalStep);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += debugTensorWatchOpts_.CalculateSize(_repeated_debugTensorWatchOpts_codec);
      if (GlobalStep != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GlobalStep);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DebugOptions other) {
      if (other == null) {
        return;
      }
      debugTensorWatchOpts_.Add(other.debugTensorWatchOpts_);
      if (other.GlobalStep != 0L) {
        GlobalStep = other.GlobalStep;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 34: {
            debugTensorWatchOpts_.AddEntriesFrom(input, _repeated_debugTensorWatchOpts_codec);
            break;
          }
          case 80: {
            GlobalStep = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
