// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/queue_runner.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/protobuf/queue_runner.proto</summary>
  public static partial class QueueRunnerReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/protobuf/queue_runner.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueueRunnerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cit0ZW5zb3JmbG93L2NvcmUvcHJvdG9idWYvcXVldWVfcnVubmVyLnByb3Rv",
            "Egp0ZW5zb3JmbG93Gip0ZW5zb3JmbG93L2NvcmUvbGliL2NvcmUvZXJyb3Jf",
            "Y29kZXMucHJvdG8iqgEKDlF1ZXVlUnVubmVyRGVmEhIKCnF1ZXVlX25hbWUY",
            "ASABKAkSFwoPZW5xdWV1ZV9vcF9uYW1lGAIgAygJEhUKDWNsb3NlX29wX25h",
            "bWUYAyABKAkSFgoOY2FuY2VsX29wX25hbWUYBCABKAkSPAoccXVldWVfY2xv",
            "c2VkX2V4Y2VwdGlvbl90eXBlcxgFIAMoDjIWLnRlbnNvcmZsb3cuZXJyb3Iu",
            "Q29kZUIyChhvcmcudGVuc29yZmxvdy5mcmFtZXdvcmtCEVF1ZXVlUnVubmVy",
            "UHJvdG9zUAH4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorflow.Error.ErrorCodesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.QueueRunnerDef), global::Tensorflow.QueueRunnerDef.Parser, new[]{ "QueueName", "EnqueueOpName", "CloseOpName", "CancelOpName", "QueueClosedExceptionTypes" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Protocol buffer representing a QueueRunner.
  /// </summary>
  public sealed partial class QueueRunnerDef : pb::IMessage<QueueRunnerDef> {
    private static readonly pb::MessageParser<QueueRunnerDef> _parser = new pb::MessageParser<QueueRunnerDef>(() => new QueueRunnerDef());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueueRunnerDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.QueueRunnerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueRunnerDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueRunnerDef(QueueRunnerDef other) : this() {
      queueName_ = other.queueName_;
      enqueueOpName_ = other.enqueueOpName_.Clone();
      closeOpName_ = other.closeOpName_;
      cancelOpName_ = other.cancelOpName_;
      queueClosedExceptionTypes_ = other.queueClosedExceptionTypes_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueueRunnerDef Clone() {
      return new QueueRunnerDef(this);
    }

    /// <summary>Field number for the "queue_name" field.</summary>
    public const int QueueNameFieldNumber = 1;
    private string queueName_ = "";
    /// <summary>
    /// Queue name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string QueueName {
      get { return queueName_; }
      set {
        queueName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enqueue_op_name" field.</summary>
    public const int EnqueueOpNameFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_enqueueOpName_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> enqueueOpName_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// A list of enqueue operations.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> EnqueueOpName {
      get { return enqueueOpName_; }
    }

    /// <summary>Field number for the "close_op_name" field.</summary>
    public const int CloseOpNameFieldNumber = 3;
    private string closeOpName_ = "";
    /// <summary>
    /// The operation to run to close the queue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CloseOpName {
      get { return closeOpName_; }
      set {
        closeOpName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cancel_op_name" field.</summary>
    public const int CancelOpNameFieldNumber = 4;
    private string cancelOpName_ = "";
    /// <summary>
    /// The operation to run to cancel the queue.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CancelOpName {
      get { return cancelOpName_; }
      set {
        cancelOpName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "queue_closed_exception_types" field.</summary>
    public const int QueueClosedExceptionTypesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Tensorflow.Error.Code> _repeated_queueClosedExceptionTypes_codec
        = pb::FieldCodec.ForEnum(42, x => (int) x, x => (global::Tensorflow.Error.Code) x);
    private readonly pbc::RepeatedField<global::Tensorflow.Error.Code> queueClosedExceptionTypes_ = new pbc::RepeatedField<global::Tensorflow.Error.Code>();
    /// <summary>
    /// A list of exception types considered to signal a safely closed queue
    /// if raised during enqueue operations.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Tensorflow.Error.Code> QueueClosedExceptionTypes {
      get { return queueClosedExceptionTypes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueueRunnerDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueueRunnerDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (QueueName != other.QueueName) return false;
      if(!enqueueOpName_.Equals(other.enqueueOpName_)) return false;
      if (CloseOpName != other.CloseOpName) return false;
      if (CancelOpName != other.CancelOpName) return false;
      if(!queueClosedExceptionTypes_.Equals(other.queueClosedExceptionTypes_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (QueueName.Length != 0) hash ^= QueueName.GetHashCode();
      hash ^= enqueueOpName_.GetHashCode();
      if (CloseOpName.Length != 0) hash ^= CloseOpName.GetHashCode();
      if (CancelOpName.Length != 0) hash ^= CancelOpName.GetHashCode();
      hash ^= queueClosedExceptionTypes_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (QueueName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(QueueName);
      }
      enqueueOpName_.WriteTo(output, _repeated_enqueueOpName_codec);
      if (CloseOpName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CloseOpName);
      }
      if (CancelOpName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CancelOpName);
      }
      queueClosedExceptionTypes_.WriteTo(output, _repeated_queueClosedExceptionTypes_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (QueueName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(QueueName);
      }
      size += enqueueOpName_.CalculateSize(_repeated_enqueueOpName_codec);
      if (CloseOpName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CloseOpName);
      }
      if (CancelOpName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CancelOpName);
      }
      size += queueClosedExceptionTypes_.CalculateSize(_repeated_queueClosedExceptionTypes_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueueRunnerDef other) {
      if (other == null) {
        return;
      }
      if (other.QueueName.Length != 0) {
        QueueName = other.QueueName;
      }
      enqueueOpName_.Add(other.enqueueOpName_);
      if (other.CloseOpName.Length != 0) {
        CloseOpName = other.CloseOpName;
      }
      if (other.CancelOpName.Length != 0) {
        CancelOpName = other.CancelOpName;
      }
      queueClosedExceptionTypes_.Add(other.queueClosedExceptionTypes_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            QueueName = input.ReadString();
            break;
          }
          case 18: {
            enqueueOpName_.AddEntriesFrom(input, _repeated_enqueueOpName_codec);
            break;
          }
          case 26: {
            CloseOpName = input.ReadString();
            break;
          }
          case 34: {
            CancelOpName = input.ReadString();
            break;
          }
          case 42:
          case 40: {
            queueClosedExceptionTypes_.AddEntriesFrom(input, _repeated_queueClosedExceptionTypes_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
