// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/tensorflow_server.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/protobuf/tensorflow_server.proto</summary>
  public static partial class TensorflowServerReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/protobuf/tensorflow_server.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TensorflowServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjB0ZW5zb3JmbG93L2NvcmUvcHJvdG9idWYvdGVuc29yZmxvd19zZXJ2ZXIu",
            "cHJvdG8SCnRlbnNvcmZsb3caJXRlbnNvcmZsb3cvY29yZS9wcm90b2J1Zi9j",
            "b25maWcucHJvdG8aJnRlbnNvcmZsb3cvY29yZS9wcm90b2J1Zi9jbHVzdGVy",
            "LnByb3RvIqUBCglTZXJ2ZXJEZWYSJwoHY2x1c3RlchgBIAEoCzIWLnRlbnNv",
            "cmZsb3cuQ2x1c3RlckRlZhIQCghqb2JfbmFtZRgCIAEoCRISCgp0YXNrX2lu",
            "ZGV4GAMgASgFEjcKFmRlZmF1bHRfc2Vzc2lvbl9jb25maWcYBCABKAsyFy50",
            "ZW5zb3JmbG93LkNvbmZpZ1Byb3RvEhAKCHByb3RvY29sGAUgASgJQi8KGm9y",
            "Zy50ZW5zb3JmbG93LmRpc3RydW50aW1lQgxTZXJ2ZXJQcm90b3NQAfgBAWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tensorflow.ConfigReflection.Descriptor, global::Tensorflow.ClusterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.ServerDef), global::Tensorflow.ServerDef.Parser, new[]{ "Cluster", "JobName", "TaskIndex", "DefaultSessionConfig", "Protocol" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Defines the configuration of a single TensorFlow server.
  /// </summary>
  public sealed partial class ServerDef : pb::IMessage<ServerDef> {
    private static readonly pb::MessageParser<ServerDef> _parser = new pb::MessageParser<ServerDef>(() => new ServerDef());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.TensorflowServerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerDef(ServerDef other) : this() {
      Cluster = other.cluster_ != null ? other.Cluster.Clone() : null;
      jobName_ = other.jobName_;
      taskIndex_ = other.taskIndex_;
      DefaultSessionConfig = other.defaultSessionConfig_ != null ? other.DefaultSessionConfig.Clone() : null;
      protocol_ = other.protocol_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerDef Clone() {
      return new ServerDef(this);
    }

    /// <summary>Field number for the "cluster" field.</summary>
    public const int ClusterFieldNumber = 1;
    private global::Tensorflow.ClusterDef cluster_;
    /// <summary>
    /// The cluster of which this server is a member.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorflow.ClusterDef Cluster {
      get { return cluster_; }
      set {
        cluster_ = value;
      }
    }

    /// <summary>Field number for the "job_name" field.</summary>
    public const int JobNameFieldNumber = 2;
    private string jobName_ = "";
    /// <summary>
    /// The name of the job of which this server is a member.
    ///
    /// NOTE(mrry): The `cluster` field must contain a `JobDef` with a `name` field
    /// that matches this name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JobName {
      get { return jobName_; }
      set {
        jobName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "task_index" field.</summary>
    public const int TaskIndexFieldNumber = 3;
    private int taskIndex_;
    /// <summary>
    /// The task index of this server in its job.
    ///
    /// NOTE: The `cluster` field must contain a `JobDef` with a matching `name`
    /// and a mapping in its `tasks` field for this index.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TaskIndex {
      get { return taskIndex_; }
      set {
        taskIndex_ = value;
      }
    }

    /// <summary>Field number for the "default_session_config" field.</summary>
    public const int DefaultSessionConfigFieldNumber = 4;
    private global::Tensorflow.ConfigProto defaultSessionConfig_;
    /// <summary>
    /// The default configuration for sessions that run on this server.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tensorflow.ConfigProto DefaultSessionConfig {
      get { return defaultSessionConfig_; }
      set {
        defaultSessionConfig_ = value;
      }
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 5;
    private string protocol_ = "";
    /// <summary>
    /// The protocol to be used by this server.
    ///
    /// Acceptable values include: "grpc".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Protocol {
      get { return protocol_; }
      set {
        protocol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Cluster, other.Cluster)) return false;
      if (JobName != other.JobName) return false;
      if (TaskIndex != other.TaskIndex) return false;
      if (!object.Equals(DefaultSessionConfig, other.DefaultSessionConfig)) return false;
      if (Protocol != other.Protocol) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cluster_ != null) hash ^= Cluster.GetHashCode();
      if (JobName.Length != 0) hash ^= JobName.GetHashCode();
      if (TaskIndex != 0) hash ^= TaskIndex.GetHashCode();
      if (defaultSessionConfig_ != null) hash ^= DefaultSessionConfig.GetHashCode();
      if (Protocol.Length != 0) hash ^= Protocol.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cluster_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Cluster);
      }
      if (JobName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(JobName);
      }
      if (TaskIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TaskIndex);
      }
      if (defaultSessionConfig_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DefaultSessionConfig);
      }
      if (Protocol.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Protocol);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cluster_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cluster);
      }
      if (JobName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JobName);
      }
      if (TaskIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskIndex);
      }
      if (defaultSessionConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DefaultSessionConfig);
      }
      if (Protocol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Protocol);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerDef other) {
      if (other == null) {
        return;
      }
      if (other.cluster_ != null) {
        if (cluster_ == null) {
          cluster_ = new global::Tensorflow.ClusterDef();
        }
        Cluster.MergeFrom(other.Cluster);
      }
      if (other.JobName.Length != 0) {
        JobName = other.JobName;
      }
      if (other.TaskIndex != 0) {
        TaskIndex = other.TaskIndex;
      }
      if (other.defaultSessionConfig_ != null) {
        if (defaultSessionConfig_ == null) {
          defaultSessionConfig_ = new global::Tensorflow.ConfigProto();
        }
        DefaultSessionConfig.MergeFrom(other.DefaultSessionConfig);
      }
      if (other.Protocol.Length != 0) {
        Protocol = other.Protocol;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (cluster_ == null) {
              cluster_ = new global::Tensorflow.ClusterDef();
            }
            input.ReadMessage(cluster_);
            break;
          }
          case 18: {
            JobName = input.ReadString();
            break;
          }
          case 24: {
            TaskIndex = input.ReadInt32();
            break;
          }
          case 34: {
            if (defaultSessionConfig_ == null) {
              defaultSessionConfig_ = new global::Tensorflow.ConfigProto();
            }
            input.ReadMessage(defaultSessionConfig_);
            break;
          }
          case 42: {
            Protocol = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
